# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 12:07
from __future__ import unicode_literals

import account.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, default=account.models.get_number, max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(8)])),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('CHF', 'CHF')], max_length=3)),
                ('balance', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
